import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js / Netlify Forms test</h1>
          <p>I&apos;m gonna be real, I love Netlify but I&apos;ve wasted TWO DAYS trying to get their forms working.</p>
          <p>This is a NO FRILLS example of a form on a next.js page to see if there&apos;s something related to my other project</p>

          <form name="contact" method="POST" data-netlify="true" encType="application/x-www-form-urlencoded">
          <input type="hidden" name="form-name" value="contact" />
            <p>
              <label>Your Name: <input type="text" name="name" /></label>
            </p>
            <p>
              <label>Your Email: <input type="email" name="email" /></label>
            </p>
            <p>
              <label>Your Role: <select name="role[]" multiple>
                <option value="leader">Leader</option>
                <option value="follower">Follower</option>
              </select></label>
            </p>
            <p>
              <label>Message: <textarea name="message"></textarea></label>
            </p>
            <p>
              <button type="submit">Send</button>
            </p>
          </form>

    <p>code taken DIRECTLY from https://docs.netlify.com/forms/setup/</p>



      </main>


    </div>
  )
}
